const employees = [
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "John",
    lastname: "Doe",
    email: "john.doe@gmail.com",
    password: "Str0ngP@ssword1!",
    gender: "Male",
    maritalStatus: "Single",
    employeeID: "EMP001",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Software Engineer",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567890",
    dateOfBirth: "1990-01-01",
    dateOfJoining: "2020-01-15",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    street: "Main St",
    houseNumber: 123,
    postalCode: "10115",
    department: "IT",
    salary: 60000,
    bankAccountDetails: {
      bankName: "Deutsche Bank",
      IBAN: "DE89370400440532012999",
      BIC: "DEUTDEDBBER",
    },
    taxIdentificationNumber: "12345678901",
    socialSecurityNumber: "12 123456 A 123",
    incomeTaxClass: 1,
    healthInsuranceCompany: "AOK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Jane",
    lastname: "Smith",
    email: "jane.smith@gmail.com",
    password: "Str0ngP@ssword2!",
    gender: "Female",
    maritalStatus: "Married",
    employeeID: "EMP002",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Product Manager",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 1,
    phoneNumber: "+491234567891",
    dateOfBirth: "1985-05-05",
    dateOfJoining: "2019-03-01",
    city: "Munich",
    state: "Bavaria",
    country: "Germany",
    street: "Second St",
    houseNumber: 456,
    postalCode: "80331",
    department: "Product",
    salary: 75000,
    bankAccountDetails: {
      bankName: "Commerzbank",
      IBAN: "DE89370400440532013001",
      BIC: "COBADEFFXXX",
    },
    taxIdentificationNumber: "12345678902",
    socialSecurityNumber: "34 567890 B 456",
    incomeTaxClass: 3,
    healthInsuranceCompany: "TK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Alice",
    lastname: "Johnson",
    email: "alice.johnson@gmail.com",
    password: "Str0ngP@ssword3!",
    gender: "Female",
    maritalStatus: "Single",
    employeeID: "EMP003",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "UX Designer",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567892",
    dateOfBirth: "1992-07-12",
    dateOfJoining: "2018-08-21",
    city: "Hamburg",
    state: "Hamburg",
    country: "Germany",
    street: "Third St",
    houseNumber: 789,
    postalCode: "20095",
    department: "Design",
    salary: 55000,
    bankAccountDetails: {
      bankName: "Sparkasse",
      IBAN: "DE89370400440532013002",
      BIC: "SPKRDEHHXXX",
    },
    taxIdentificationNumber: "12345678903",
    socialSecurityNumber: "56 789012 C 789",
    incomeTaxClass: 1,
    healthInsuranceCompany: "Barmer",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Bob",
    lastname: "Williams",
    email: "bob.williams@gmail.com",
    password: "Str0ngP@ssword4!",
    gender: "Male",
    maritalStatus: "Divorced",
    employeeID: "EMP004",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "DevOps Engineer",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 2,
    phoneNumber: "+491234567893",
    dateOfBirth: "1980-11-30",
    dateOfJoining: "2017-02-10",
    city: "Frankfurt",
    state: "Hesse",
    country: "Germany",
    street: "Fourth St",
    houseNumber: 101,
    postalCode: "60311",
    department: "IT",
    salary: 65000,
    bankAccountDetails: {
      bankName: "ING-DiBa",
      IBAN: "DE89370400440532013003",
      BIC: "INGDDEFFXXX",
    },
    taxIdentificationNumber: "12345678904",
    socialSecurityNumber: "78 901234 D 012",
    incomeTaxClass: 2,
    healthInsuranceCompany: "DAK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Charlie",
    lastname: "Brown",
    email: "charlie.brown@gmail.com",
    password: "Str0ngP@ssword5!",
    gender: "Male",
    maritalStatus: "Single",
    employeeID: "EMP005",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Data Scientist",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567894",
    dateOfBirth: "1995-03-14",
    dateOfJoining: "2021-06-25",
    city: "Cologne",
    state: "North Rhine-Westphalia",
    country: "Germany",
    street: "Fifth St",
    houseNumber: 202,
    postalCode: "50667",
    department: "Data",
    salary: 70000,
    bankAccountDetails: {
      bankName: "Postbank",
      IBAN: "DE89370400440532013004",
      BIC: "PBNKDEFFXXX",
    },
    taxIdentificationNumber: "12345678905",
    socialSecurityNumber: "90 123456 E 345",
    incomeTaxClass: 1,
    healthInsuranceCompany: "AOK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "David",
    lastname: "Davis",
    email: "david.davis@gmail.com",
    password: "Str0ngP@ssword6!",
    gender: "Male",
    maritalStatus: "Married",
    employeeID: "EMP006",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "HR Manager",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 3,
    phoneNumber: "+491234567895",
    dateOfBirth: "1978-09-09",
    dateOfJoining: "2016-11-01",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    country: "Germany",
    street: "Sixth St",
    houseNumber: 303,
    postalCode: "70173",
    department: "HR",
    salary: 75000,
    bankAccountDetails: {
      bankName: "Volksbank",
      IBAN: "DE89370400440532013005",
      BIC: "GENODEF1VBD",
    },
    taxIdentificationNumber: "12345678906",
    socialSecurityNumber: "12 345678 F 678",
    incomeTaxClass: 3,
    healthInsuranceCompany: "TK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Emma",
    lastname: "Wilson",
    email: "emma.wilson@gmail.com",
    password: "Str0ngP@ssword7!",
    gender: "Female",
    maritalStatus: "Single",
    employeeID: "EMP007",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Marketing Specialist",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567896",
    dateOfBirth: "1998-12-25",
    dateOfJoining: "2022-01-10",
    city: "Düsseldorf",
    state: "North Rhine-Westphalia",
    country: "Germany",
    street: "Seventh St",
    houseNumber: 404,
    postalCode: "40213",
    department: "Marketing",
    salary: 50000,
    bankAccountDetails: {
      bankName: "KfW",
      IBAN: "DE89370400440532013006",
      BIC: "KFWIDFFXXX",
    },
    taxIdentificationNumber: "12345678907",
    socialSecurityNumber: "34 567890 G 901",
    incomeTaxClass: 1,
    healthInsuranceCompany: "Barmer",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Fiona",
    lastname: "Taylor",
    email: "fiona.taylor@gmail.com",
    password: "Str0ngP@ssword8!",
    gender: "Female",
    maritalStatus: "Married",
    employeeID: "EMP008",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Finance Manager",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 2,
    phoneNumber: "+491234567897",
    dateOfBirth: "1986-04-18",
    dateOfJoining: "2015-05-12",
    city: "Leipzig",
    state: "Saxony",
    country: "Germany",
    street: "Eighth St",
    houseNumber: 505,
    postalCode: "04109",
    department: "Finance",
    salary: 80000,
    bankAccountDetails: {
      bankName: "HypoVereinsbank",
      IBAN: "DE89370400440532013007",
      BIC: "HYVEDEMMXXX",
    },
    taxIdentificationNumber: "12345678908",
    socialSecurityNumber: "56 789012 H 234",
    incomeTaxClass: 3,
    healthInsuranceCompany: "DAK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "George",
    lastname: "Martinez",
    email: "george.martinez@gmail.com",
    password: "Str0ngP@ssword9!",
    gender: "Male",
    maritalStatus: "Widowed",
    employeeID: "EMP009",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Business Analyst",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 1,
    phoneNumber: "+491234567898",
    dateOfBirth: "1975-10-23",
    dateOfJoining: "2014-07-04",
    city: "Bremen",
    state: "Bremen",
    country: "Germany",
    street: "Ninth St",
    houseNumber: 606,
    postalCode: "28195",
    department: "Business",
    salary: 65000,
    bankAccountDetails: {
      bankName: "Targobank",
      IBAN: "DE89370400440532013008",
      BIC: "TARGDEFFXXX",
    },
    taxIdentificationNumber: "12345678909",
    socialSecurityNumber: "78 901234 I 567",
    incomeTaxClass: 2,
    healthInsuranceCompany: "AOK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Hannah",
    lastname: "Garcia",
    email: "hannah.garcia@gmail.com",
    password: "Str0ngP@ssword10!",
    gender: "Female",
    maritalStatus: "Single",
    employeeID: "EMP010",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Sales Manager",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567899",
    dateOfBirth: "1993-02-15",
    dateOfJoining: "2020-03-10",
    city: "Hanover",
    state: "Lower Saxony",
    country: "Germany",
    street: "Tenth St",
    houseNumber: 707,
    postalCode: "30159",
    department: "Sales",
    salary: 60000,
    bankAccountDetails: {
      bankName: "Deutsche Bank",
      IBAN: "DE89370400440532013009",
      BIC: "DEUTDEDBHAN",
    },
    taxIdentificationNumber: "12345678910",
    socialSecurityNumber: "90 123456 J 890",
    incomeTaxClass: 1,
    healthInsuranceCompany: "TK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Ivy",
    lastname: "Miller",
    email: "ivy.miller@gmail.com",
    password: "Str0ngP@ssword11!",
    gender: "Female",
    maritalStatus: "Divorced",
    employeeID: "EMP011",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Support Engineer",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 1,
    phoneNumber: "+491234567900",
    dateOfBirth: "1982-06-22",
    dateOfJoining: "2013-09-15",
    city: "Dresden",
    state: "Saxony",
    country: "Germany",
    street: "Eleventh St",
    houseNumber: 808,
    postalCode: "01067",
    department: "Support",
    salary: 55000,
    bankAccountDetails: {
      bankName: "Commerzbank",
      IBAN: "DE89370400440532013010",
      BIC: "COBADEFFXXX",
    },
    taxIdentificationNumber: "12345678911",
    socialSecurityNumber: "12 345678 K 123",
    incomeTaxClass: 2,
    healthInsuranceCompany: "Barmer",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Jack",
    lastname: "Anderson",
    email: "jack.anderson@gmail.com",
    password: "Str0ngP@ssword12!",
    gender: "Male",
    maritalStatus: "Married",
    employeeID: "EMP012",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Network Administrator",
    employmentType: "Full-time",
    employmentStatus: "Active",
    noOfChildren: 2,
    phoneNumber: "+491234567901",
    dateOfBirth: "1987-08-08",
    dateOfJoining: "2012-11-20",
    city: "Nuremberg",
    state: "Bavaria",
    country: "Germany",
    street: "Twelfth St",
    houseNumber: 909,
    postalCode: "90402",
    department: "IT",
    salary: 60000,
    bankAccountDetails: {
      bankName: "Sparkasse",
      IBAN: "DE89370400440532013011",
      BIC: "SPKRDEFFXXX",
    },
    taxIdentificationNumber: "12345678912",
    socialSecurityNumber: "34 567890 L 456",
    incomeTaxClass: 3,
    healthInsuranceCompany: "DAK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Karen",
    lastname: "Thomas",
    email: "karen.thomas@gmail.com",
    password: "Str0ngP@ssword13!",
    gender: "Female",
    maritalStatus: "Single",
    employeeID: "EMP013",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Content Writer",
    employmentType: "Part-time",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567902",
    dateOfBirth: "1999-05-20",
    dateOfJoining: "2023-04-15",
    city: "Kiel",
    state: "Schleswig-Holstein",
    country: "Germany",
    street: "Thirteenth St",
    houseNumber: 1010,
    postalCode: "24103",
    department: "Content",
    salary: 30000,
    bankAccountDetails: {
      bankName: "Postbank",
      IBAN: "DE89370400440532013012",
      BIC: "PBNKDEFFXXX",
    },
    taxIdentificationNumber: "12345678913",
    socialSecurityNumber: "56 789012 M 789",
    incomeTaxClass: 1,
    healthInsuranceCompany: "AOK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Liam",
    lastname: "Moore",
    email: "liam.moore@gmail.com",
    password: "Str0ngP@ssword14!",
    gender: "Male",
    maritalStatus: "Single",
    employeeID: "EMP014",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Intern",
    employmentType: "Internship",
    employmentStatus: "Active",
    noOfChildren: 0,
    phoneNumber: "+491234567903",
    dateOfBirth: "2001-11-11",
    dateOfJoining: "2023-06-01",
    city: "Potsdam",
    state: "Brandenburg",
    country: "Germany",
    street: "Fourteenth St",
    houseNumber: 1111,
    postalCode: "14467",
    department: "Intern",
    salary: 15000,
    bankAccountDetails: {
      bankName: "ING-DiBa",
      IBAN: "DE89370400440532013013",
      BIC: "INGDDEFFXXX",
    },
    taxIdentificationNumber: "12345678914",
    socialSecurityNumber: "78 901234 N 012",
    incomeTaxClass: 1,
    healthInsuranceCompany: "TK",
  },
  {
    profilePicture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/320px-User-avatar.svg.png",
    firstname: "Mia",
    lastname: "White",
    email: "mia.white@gmail.com",
    password: "Str0ngP@ssword15!",
    gender: "Female",
    maritalStatus: "Widowed",
    employeeID: "EMP015",
    companyId: "COMP123",
    companyName: "Tech Solutions",
    jobTitle: "Office Assistant",
    employmentType: "Part-time",
    employmentStatus: "Active",
    noOfChildren: 2,
    phoneNumber: "+491234567904",
    dateOfBirth: "1972-02-28",
    dateOfJoining: "2021-08-10",
    city: "Mannheim",
    state: "Baden-Württemberg",
    country: "Germany",
    street: "Fifteenth St",
    houseNumber: 1212,
    postalCode: "68159",
    department: "Admin",
    salary: 35000,
    bankAccountDetails: {
      bankName: "Volksbank",
      IBAN: "DE89370400440532013014",
      BIC: "GENODEF1VBD",
    },
    taxIdentificationNumber: "12345678915",
    socialSecurityNumber: "90 123456 O 345",
    incomeTaxClass: 2,
    healthInsuranceCompany: "DAK",
  },
];

export default employees;
